INSERT INTO USER_ACTION_LOG(user_id)  VALUES(10023);
INSERT INTO USER_ACTION_LOG(user_id)  VALUES(10024);
INSERT INTO USER_ACTION_LOG(user_id)  VALUES(10025);
INSERT INTO USER_ACTION_LOG(user_id)  VALUES(10026);