spring.datasource:
  plarform: h2
  # driverClassName: org.h2.Driver
  # url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:application}
  username: ${MYSQL_ROOT_USER:root}
  password: ${MYSQL_ROOT_PASSWORD:root}
  initialize: true # classpath:/schema.sql, import.sql, data.sql

  ## Pool Info ##
  validationQuery: SELECT 1
  testOnBorrow: true
  testOnReturn: false
  maxActive: 10
  maxIdle: 10
  minIdle: 10
  initialSize: 20
  timeBetweenEvictionRunsMillis: 5000 #5 second
  minEvictableIdleTimeMillis: 10000   #10 second
  validationQueryTimeout: 5

# DB - JPA
spring.jpa:
  database: MYSQL
  show-sql: true
  properties.hibernate.hbm2ddl.auto: update # create, update, none, validate
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true
